spring.application.name=EasyFix

spring.profiles.active = true
#spring.sql.init.mode=never

server.error.include-stacktrace=ALWAYS
server.port=8080
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/easyfix
spring.datasource.username={{YOUR USERNAME}}
spring.datasource.password={{YOUR PASSWORD}}

spring.jpa.show-sql=true

jwt-secret={{JWT SECRET}}
jwt-expiration-ms = 86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={{YOUR EMAIL}}
spring.mail.password={{YOUR PASSWORD}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true